
spring:
  h2:console.enabled: true
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: